language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install coverage coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source=wcfg.py setup.py test
after_success: coveralls
